const destinationsFromTashkentRu = [
    "Ташкент", "Москва", "Санкт-Петербург", "Новосибирск", "Екатеринбург", "Казань", "Самара", "Челябинск",
    "Нижний Новгород", "Ростов-на-Дону", "Уфа", "Волгоград", "Красноярск", "Пермь", "Воронеж", "Саратов",
    "Тюмень", "Омск", "Калининград", "Краснодар", "Набережные Челны", "Ижевск", "Барнаул", "Тольятти",
    "Ульяновск", "Иркутск", "Владивосток", "Ярославль", "Хабаровск", "Махачкала", "Оренбург", "Кемерово",
    "Новокузнецк", "Рязань", "Астрахань", "Нижний Тагил", "Пенза", "Тверь", "Сургут", "Киров", "Мурманск",
    "Ставрополь", "Тула", "Белгород", "Курск", "Владимир", "Чебоксары", "Калуга", "Астана", "Орёл", "Смоленск",
    "Курган", "Сыктывкар", "Саранск", "Волжский", "Иваново", "Томск", "Петрозаводск", "Йошкар-Ола",
    "Новороссийск", "Вологда", "Салават", "Магнитогорск", "Якутск", "Нефтекамск", "Владикавказ",
    "Архангельск", "Великий Новгород", "Грозный", "Северодвинск", "Элиста", "Кызыл", "Чита",
    "Брянск", "Нижнекамск", "Муром", "Кострома", "Рыбинск", "Таганрог",
    "Анапа", "Сочи", "Адлер", "Геленджик", "Ереван", "Баку", "Тбилиси", "Алматы", "Нур-Султан",
    "Шымкент", "Актобе", "Караганда", "Бишкек", "Оша", "Душанбе", "Худжанд", "Бангкок", "Сингапур",
    "Куала-Лумпур", "Дубай", "Абу-Даби", "Абу Даби", "Шарджа", "Стамбул", "Анкара", "Измир", "София", "Бухарест",
    "Братислава", "Прага", "Вена", "Будапешт", "Берлин", "Мюнхен", "Франкфурт", "Гамбург", "Кёльн",
    "Дюссельдорф", "Амстердам", "Роттердам", "Лондон", "Манчестер", "Бирмингем", "Эдинбург",
    "Дублин", "Париж", "Лион", "Марсель", "Ницца", "Барселона", "Мадрид", "Валенсия", "Севилья",
    "Рим", "Милан", "Неаполь", "Флоренция", "Венеция", "Турин", "Болонья", "Наполи", "Лиссабон",
    "Порту", "Брюссель", "Антверпен", "Гент", "Цюрих", "Женева", "Базель", "Лозанна", "Осло",
    "Стокгольм", "Гетеборг", "Мальме", "Хельсинки", "Таллин", "Рига", "Вильнюс", "Копенгаген",
    "Афины", "Салоники", "Сантьяго", "Буэнос-Айрес", "Рио-де-Жанейро", "Сан-Паулу", "Мехико",
    "Канкун", "Гвадалахара", "Монтеррей", "Нью-Йорк", "Лос-Анджелес", "Чикаго", "Майами", "Бостон",
    "Вашингтон", "Сан-Франциско", "Сиэтл", "Лас-Вегас", "Торонто", "Ванкувер", "Монреаль", "Оттава",
    "Кейптаун", "Йоханнесбург", "Дурбан", "Каир", "Хургада", "Александрия", "Мускат", "Манама",
    "Эль-Кувейт", "Доха", "Сеул", "Токио", "Осака", "Нагоя", "Саппоро", "Киото", "Хиросима",
    "Пекин", "Шанхай", "Гуанчжоу", "Шэньчжэнь", "Ханчжоу", "Ханой", "Хошимин", "Дели", "Мумбаи",
    "Бангалор", "Ченнай", "Колката", "Карачи", "Исламабад", "Лахор", "Тель-Авив", "Иерусалим",
    "Амман", "Бейрут", "Касабланка", "Рабат", "Марракеш", "Джидда", "Медина", "Рияд", "Катар",
    "Минск", "Варшава", "Астана",
];


const destinationsFromTashkentLat = [
    "Tashkent", "Moskva", "Sankt-Peterburg", "Novosibirsk", "Ekaterinburg", "Kazan", "Samara", "Chelyabinsk",
    "Nizhniy Novgorod", "Rostov-na-Donu", "Ufa", "Volgograd", "Krasnoyarsk", "Perm", "Voronezh", "Saratov",
    "Tyumen", "Omsk", "Kaliningrad", "Krasnodar", "Naberezhnye Chelny", "Izhevsk", "Barnaul", "Tolyatti",
    "Ulyanovsk", "Irkutsk", "Vladivostok", "Yaroslavl", "Khabarovsk", "Makhachkala", "Orenburg", "Kemerovo",
    "Novokuznetsk", "Ryazan", "Astrakhan", "Nizhniy Tagil", "Penza", "Tver", "Surgut", "Kirov", "Murmansk",
    "Stavropol", "Tula", "Belgorod", "Kursk", "Vladimir", "Cheboksary", "Kaluga", "Astana", "Oryol", "Smolensk",
    "Kurgan", "Syktyvkar", "Saransk", "Volzhsky", "Ivanovo", "Tomsk", "Petrozavodsk", "Yoshkar-Ola",
    "Novorossiysk", "Vologda", "Salavat", "Magnitogorsk", "Yakutsk", "Neftekamsk", "Vladikavkaz",
    "Arkhangelsk", "Velikiy Novgorod", "Grozny", "Severodvinsk", "Elista", "Kyzyl", "Chita",
    "Bryansk", "Nizhnekamsk", "Murom", "Kostroma", "Rybinsk", "Taganrog",
    "Anapa", "Sochi", "Adler", "Gelendzhik", "Yerevan", "Boku", "Tbilisi", "Almaty", "Nur-Sultan",
    "Shymkent", "Aktobe", "Karaganda", "Bishkek", "Osh", "Dushanbe", "Khujand", "Bangkok", "Singapore",
    "Kuala-Lumpur", "Dubai", "Abu-Dhabi", "Abu-Dhabi", "Sharjah", "Istanbul", "Ankara", "Izmir", "Sofia", "Bucharest",
    "Bratislava", "Prague", "Vienna", "Budapest", "Berlin", "Munich", "Frankfurt", "Hamburg", "Koln",
    "Dusseldorf", "Amsterdam", "Rotterdam", "London", "Manchester", "Birmingham", "Edinburgh",
    "Dublin", "Paris", "Lyon", "Marseille", "Nice", "Barcelona", "Madrid", "Valencia", "Seville",
    "Rome", "Milan", "Naples", "Florence", "Venice", "Turin", "Bologna", "Lisbon",
    "Porto", "Brussels", "Antwerp", "Ghent", "Zurich", "Geneva", "Basel", "Lausanne", "Oslo",
    "Stockholm", "Gothenburg", "Malmo", "Helsinki", "Tallinn", "Riga", "Vilnius", "Copenhagen",
    "Athens", "Thessaloniki", "Santiago", "Buenos Aires", "Rio de Janeiro", "Sao Paulo", "Mexico City",
    "Cancun", "Guadalajara", "Monterrey", "New York", "Los Angeles", "Chicago", "Miami", "Boston",
    "Washington", "San Francisco", "Seattle", "Las Vegas", "Toronto", "Vancouver", "Montreal", "Ottawa",
    "Cape Town", "Johannesburg", "Durban", "Cairo", "Hurghada", "Alexandria", "Muscat", "Manama",
    "El-Kuwait", "Doha", "Seoul", "Tokyo", "Osaka", "Nagoya", "Sapporo", "Kyoto", "Hiroshima",
    "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Hangzhou", "Hanoi", "Ho Chi Minh",
    "Delhi", "Mumbai", "Bangalore", "Chennai", "Kolkata", "Karachi", "Islamabad", "Lahore",
    "Tel Aviv", "Jerusalem", "Amman", "Beirut", "Casablanca", "Rabat", "Marrakech", "Jeddah",
    "Medina", "Riyadh", "Qatar", "Minsk", "Warsaw", 
];


export {
    destinationsFromTashkentLat,
    destinationsFromTashkentRu
}
