const countries = [
    "UZBEKISTAN",
    "KAZAKHSTAN",
    "RUSSIA",
    "BELARUS",
    "TAJIKISTAN",
    "KYRGYZSTAN",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "ALBANIA",
    "ALGERIA",
    "ANGOLA",
    "ANDORRA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "AFGHANISTAN",
    "BAHAMAS",
    "BANGLADESH",
    "BARBADOS",
    "BAHRAIN",
    "BELIZE",
    "BELGIUM",
    "BENIN",
    "BULGARIA",
    "BOLIVIA",
    "BOSNIA AND HERZEGOVINA",
    "BOTSWANA",
    "BRAZIL",
    "BRUNEI",
    "BURKINA FASO",
    "BURUNDI",
    "BHUTAN",
    "VANUATU",
    "UNITED KINGDOM",
    "HUNGARY",
    "VENEZUELA",
    "EAST TIMOR",
    "VIETNAM",
    "GABON",
    "HAITI",
    "GUYANA",
    "GAMBIA",
    "GHANA",
    "GUATEMALA",
    "GUINEA",
    "GUINEA-BISSAU",
    "GERMANY",
    "HONDURAS",
    "GRENADA",
    "GREECE",
    "GEORGIA",
    "DENMARK",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "EGYPT",
    "ZAMBIA",
    "ZIMBABWE",
    "ISRAEL",
    "INDIA",
    "INDONESIA",
    "JORDAN",
    "IRAQ",
    "IRAN",
    "IRELAND",
    "ICELAND",
    "SPAIN",
    "ITALY",
    "YEMEN",
    "CABO VERDE",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "QATAR",
    "KENYA",
    "CYPRUS",
    "KIRIBATI",
    "CHINA",
    "COLOMBIA",
    "COMOROS",
    "CONGO",
    "DEMOCRATIC REPUBLIC OF THE CONGO",
    "NORTH KOREA",
    "SOUTH KOREA",
    "COSTA RICA",
    "COTE D'IVOIRE",
    "CUBA",
    "KUWAIT",
    "LAOS",
    "LATVIA",
    "LESOTHO",
    "LIBERIA",
    "LEBANON",
    "LIBYA",
    "LITHUANIA",
    "LIECHTENSTEIN",
    "LUXEMBOURG",
    "MAURITIUS",
    "MAURITANIA",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALI",
    "MALDIVES",
    "MALTA",
    "MOROCCO",
    "MARSHALL ISLANDS",
    "MEXICO",
    "MICRONESIA",
    "MOZAMBIQUE",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MYANMAR",
    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NIGER",
    "NIGERIA",
    "NETHERLANDS",
    "NICARAGUA",
    "NEW ZEALAND",
    "NORWAY",
    "UNITED ARAB EMIRATES",
    "OMAN",
    "PAKISTAN",
    "PALAU",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "POLAND",
    "PORTUGAL",
    "RWANDA",
    "ROMANIA",
    "EL SALVADOR",
    "SAMOA",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "NORTH MACEDONIA",
    "SEYCHELLES",
    "SENEGAL",
    "SAINT VINCENT AND THE GRENADINES",
    "SAINT KITTS AND NEVIS",
    "SAINT LUCIA",
    "SERBIA",
    "SINGAPORE",
    "SYRIA",
    "SLOVAKIA",
    "SLOVENIA",
    "UNITED STATES OF AMERICA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SUDAN",
    "SURINAME",
    "SIERRA LEONE",
    "THAILAND",
    "TANZANIA",
    "TOGO",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUVALU",
    "TUNISIA",
    "TURKMENISTAN",
    "TURKEY",
    "UGANDA",
    "UKRAINE",
    "URUGUAY",
    "FIJI",
    "PHILIPPINES",
    "FINLAND",
    "FRANCE",
    "CROATIA",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "MONTENEGRO",
    "CZECH REPUBLIC",
    "CHILE",
    "SWITZERLAND",
    "SWEDEN",
    "SRI LANKA",
    "ECUADOR",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESWATINI",
    "ESTONIA",
    "ETHIOPIA",
    "SOUTH AFRICA",
    "SOUTH SUDAN",
    "JAMAICA",
    "JAPAN"
];

    

export default countries;